version: "3"
services:
  postgres:
    image: postgres:16rc1
    restart: always
    environment:
      - POSTGRES_DB=conferenceplanner
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - postgres:/var/lib/postgresql/data
      - ./Database:/docker-entrypoint-initdb.d
  app:
    depends_on:
      - postgres
    image: sethbrittain/conferenceplanner:1.0.0
    restart: always
    ports:
      - 80:80
volumes:
  postgres:
    driver: local
