version: "3"
services:
  postgres:
    image: postgres:16rc1
    container_name: conferenceplanner_database
    hostname: conferenceplanner_database
    restart: always
    environment:
      - POSTGRES_DB=conferenceplanner
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - postgres:/var/lib/postgresql/data
      - ./Database:/docker-entrypoint-initdb.d
  app:
    depends_on:
      - postgres
    image: sethbrittain/conferenceplanner:1.0.0
    container_name: conferenceplanner_app
    hostname: conferenceplanner_app
    restart: always
    ports:
      - 5000:5000
volumes:
  postgres:
    driver: local
